### ISSUE TITLE
feat(lang): Support TensorBoard

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#527] opened 2022-06-29 14:22 UTC
## Description

```python
def build():
  config.tensorboard(port="8888", log_dir="./logs")
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment] 2022-06-29 14:28
I am not sure if we should support framework-specific functions. Perhaps we should make it generic to expose any services instead.

**Comment by aseaday** [comment] 2022-06-29 18:10
I think there are some questions to discuss:
- Should users care about the port? if we listen on the host's interface, user A use port 8888 but user B used it already.
- Which interface should be listening ,the container or the host.
- Which address? Loopback or external ip?
We should anwser the above questions to design the service function.
In my opinon, we should sperate the service and the service provider(such as Service and Deployment in K8S).

```python
class JuypterSvc(Service):
  port = 8000
  interfaceLoc = container
  ip = 0.0.0.0
def build():
  config.juypter(service=JuypterSvc)
```

**Comment by gaocegege** [comment] 2022-06-30 01:31
> Should users care about the port? if we listen on the host's interface, user A use port 8888 but user B used it already.

I think in the best case, users do not need care about the port. He can use the endpoint provided by envd to visit these services.

> Which interface should be listening ,the container or the host.

Currently, we keep port in the container open and use docker port forwarding to forward container ports to host.

> Which address? Loopback or external IP?

Since we forward container port to host, thus localhost can be used here. I am not sure if it works for WSL @VoVAllen

**Comment by VoVAllen** [comment] 2022-06-30 05:19
WSL will automatically make ports available to host os (windows).

We definitely need a way for users to easily extend their use cases. However, the grammar may need more discussions.

**Comment by kemingy** [comment] 2022-08-17 06:39
Since `envd` already supports `expose`, `daemon`, `mount`, I think it can be done in the following way:

```py
def tensorboard():
    io.mount(src="/var/log/tensorboard", dest="./logs")
    runtime.daemon(commands=[
        ["tensorboard", "--logdir", "./logs", "--port", "8888"],
    ]),
    runtime.expose(envd_port=8888, host_port=8888, service="tensorboard")
```

Shall we close this issue? @gaocegege

**Comment by aseaday** [comment] 2022-08-17 06:41
All we need is code snipplet

**Comment by gaocegege** [comment] 2022-08-17 08:23
Ref #91 

I think we can close it after the doc is updated, WDYT.

**Comment by gaocegege** [comment] 2022-08-17 08:26
In the future, I think we should have the mechanism to make these starlark funcs built-in in envd.

**Comment by gaocegege** [comment] 2022-08-17 12:44
> Since `envd` already supports `expose`, `daemon`, `mount`, I think it can be done in the following way:
> 
> ```python
> def tensorboard():
>     io.mount(src="/var/log/tensorboard", dest="./logs")
>     runtime.daemon(commands=[
>         ["tensorboard", "--logdir", "./logs", "--port", "8888"],
>     ]),
>     runtime.expose(envd_port=8888, host_port=8888, service="tensorboard")
> ```
> 
> Shall we close this issue? @gaocegege

I got this error 

```
error: invalid mount config for type "bind": invalid mount path: './logs' mount path must be absolute
```

**Comment by zwpaper** [comment] 2022-08-17 16:28
it is caused by `dest="./logs"`, docker doesn't allow relative mount path.

should we expand the relative path to an absolute one?

**Comment by aseaday** [comment] 2022-08-17 16:32
Maybe we could had a default cwd directory and allow users to override. WDYT?

**Comment by zwpaper** [comment] 2022-08-17 16:36
of cause, just like docker can specify a building dir, it should be the cwd.

**Comment by gaocegege** [comment] 2022-08-18 01:57
The dest arg specifies the location inside the container, default cwd may not work for this.

I think we can define the working directory in envd, then expand the relative paths to absolute paths.

**Closed** 2022-08-19 01:51 UTC
Labels: priority/2-medium 💛, type/enhancement 💭, type/feature 💡, area/lang 🌐, difficulty/medium
