### ISSUE TITLE
feat: podman support?

### ISSUE THREAD

**Issue by TaylorHere** [tensorchord/envd#915] opened 2022-09-16 18:06 UTC
## Description

should we plan to support [podman](https://podman.io/)?  
for Linux users, podman may be their best choice for managing containers and images.  
also for macOS users, [podman is  available now](https://marcusnoble.co.uk/2021-09-01-migrating-from-docker-to-podman/).  
podman can run without a daemon service and sudo permission.  
supporting podman may increase the user experience by hidding `containers` under the hood

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by gaocegege** [comment] 2022-09-17 01:37
Yep, See here https://github.com/tensorchord/envd/issues/282

The issue is dup, I am closing it. Let's discuss in the issue #282

**Closed by gaocegege** 2022-09-17 01:37 UTC
Labels: type/documentation 📄, type/enhancement 💭, type/feature 💡, os/linux, os/macOS, area/docker 🐳
