### ISSUE TITLE
bug: <title> No such image after envd up

### ISSUE THREAD

**Issue by sea-wyq** [tensorchord/envd#711] opened 2022-08-03 08:11 UTC
## Description
First execute envd up --t test , then delete the mirror test, and finally execute envd up --t test There will be an error error: No such image:test , showing that the cached image after deletion can be read。
## Additional Info
![image](https://user-images.githubusercontent.com/22475606/182558237-9fee4dfd-6121-40d2-84f3-912056a3bd9c.png)
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gaocegege** [comment] 2022-08-03 11:02
Thanks for the issue, we will take a look.

**Comment by kemingy** [comment] 2022-08-08 01:45
What does "then delete the mirror test" mean?

I cannot reproduce this by the following commands:

```console
envd up -t debug:test
(exit the container)
envd destroy
docker image rm <digest>
envd up -t debug:test
```

**Comment by sea-wyq** [comment] 2022-08-08 01:54
destroy is not executed

**Comment by kemingy** [comment] 2022-08-08 01:56
> destroy is not executed

Then there should be a warning:

```console
Error response from daemon: conflict: unable to delete 4f046a4e9536 (cannot be forced) - image is being used by running container e9c97087449e
```

You should not be able to delete the image since it's been used.

**Comment by kemingy** [comment] 2022-11-10 09:06
It's similar to https://github.com/tensorchord/envd/issues/1165#issuecomment-1305039165.

I think we can close this. But feel free to reopen this if you find any other similar situations.

**Closed by kemingy** 2022-11-10 09:06 UTC
Labels: type/bug 🐛, status/cannot-reproduce
